from django.urls import path
from . import views

urlpatterns = [
    path('', views.rd),
    path('home', views.home, name='home'),
    path('uploading', views.uploading, name='uploading'),
    path('success', views.success, name='success'),
    path('show_csv', views.show_csv, name='show_csv'),
    path('data', views.data, name='data'),
    path('chart', views.chart, name='chart'),
    path('gender', views.gender, name='gender'),
    path('SeniorCitizen', views.SeniorCitizen, name='SeniorCitizen'),
    path('Partner', views.Partner, name='Partner'),
    path('Dependents', views.Dependents, name='Dependents'),
    path('PhoneService', views.PhoneService, name='PhoneService'),
    path('MultipleLines', views.MultipleLines, name='MultipleLines'),
    path('InternetService', views.InternetService, name='InternetService'),
    path('OnlineSecurity', views.OnlineSecurity, name='OnlineSecurity'),
    path('OnlineBackup', views.OnlineBackup, name='OnlineBackup'),
    path('DeviceProtection', views.DeviceProtection, name='DeviceProtection'),
    path('TechSupport', views.TechSupport, name='TechSupport'),
    path('StreamingTV', views.StreamingTV, name='StreamingTV'),
    path('StreamingMovies', views.StreamingMovies, name='StreamingMovies'),
    path('Contract', views.Contract, name='Contract'),
    path('PaperlessBilling', views.PaperlessBilling, name='PaperlessBilling'),
    path('PaymentMethod', views.PaymentMethod, name='PaymentMethod'),
    path('tenure', views.tenure, name='tenure'),
    path('MonthlyCharges', views.MonthlyCharges, name='MonthlyCharges'),
    path('TotalCharges', views.TotalCharges, name='TotalCharges'),
    path('Logistic_Regression', views.Logistic_Regression, name='Logistic_Regression'),
    path('X_train', views.X_train, name='X_train'),
    path('Y_train', views.Y_train, name='Y_train'),
    path('X_test', views.X_test, name='X_test'),
    path('Y_test', views.Y_test, name='Y_test'),
    path('waiting', views.waiting, name='waiting'),
    path('select_show', views.select_show, name='select_show'),
    path('final', views.final, name='final'),
]